name = "pkg-atlantic-sh"
main = "infra/cloudflare/src/index.js"
compatibility_date = "2024-09-01"

[vars]
GITHUB_REPO = "brasga-a/pkg"
DEFAULT_BRANCH = "main"
CACHE_TTL = "300"

routes = [
  { pattern = "pkg.atlantic.sh", custom_domain = true }
]
